### ISSUE TITLE
Double declaration of .btn-default

### ISSUE THREAD

**Issue by beld78** [dreamRs/fresh#6]
Is there a reason why there are 2 different CSS specifications for the .btn-default class?

```css
.btn-default {
	color: #333;
	background-color: #fff;
	border-color: #ccc
.btn-default {
	background-color: #f4f4f4;
	color: #444;
	border-color: #ddd
}
}
```
I found this in my generated CSS
